GRANT CREATE DBT PROJECT ON SCHEMA TASTY_BYTES_DBT_DB.DEV TO ROLE my_role;
GRANT CREATE DBT PROJECT ON SCHEMA TASTY_BYTES_DBT_DB.PROD TO ROLE my_role;

GRANT OWNERSHIP ON DBT PROJECT TASTY_BYTES_DBT_PROJECT TO ROLE my_role;

GRANT USAGE ON DBT PROJECT TASTY_BYTES_DBT_PROJECT TO ROLE my_role;

GRANT MONITOR ON DBT PROJECT TASTY_BYTES_DBT_PROJECT TO ROLE my_role;